Change dev-install to avoid dependency conflicts
This is sub-optimal, but working. Basically, with the old command we
routinely had conflicts like

```console
$ pip-sync --verbose requirements/*.txt -n
Using pip-tools configuration defaults found in 'pyproject.toml'.
Incompatible requirements found: markdown-it-py==3.0.0 (from -r requirements/prod.txt (line 48)) and markdown-it-py==2.2.0 (from -r requirements/dev.txt (line 116))
```

We managed to get into this state because we're no longer using
`requirements/prod.txt` as a constraints file. If we try to do so we
see:

```console
$ pip-compile --output-file=requirements/dev.txt -c requirements/prod.txt --all-extras pyproject.toml
/Users/jestevez/work/rel/CumulusCI/.direnv/python-3.8.16/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
  ERROR: Cannot install cumulusci (pyproject.toml) because these package versions have conflicting dependencies.
```

The blocking dependency is vcrpy, which pins urllib3 on python versions
<3.10. Because dependencies are built on 3.8, dev dependencies are
pinned at 1.26.15 while prod is pinned at 2.0.4...

This puts us in the position of testing a fixed set of dependencies
across all environments (OS and Python version/implementation) we support. The options
as I see them are to either let the test dependencies float, or use
pip-compile to generate requirements files for each environment. The
latter is probably what we should have been doing [all along], but it's
more code to maintain.

[all along]: https://pip-tools.readthedocs.io/en/latest/#cross-environment-usage-of-requirements-in-requirements-txt-and-pip-compile