Add Rust as build dependency in homebrew formula
Users were intermittently reporting that upgrades failed with some
variation of the following error:

```python-traceback
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
     exec(compile(code, __file__, 'exec'), locals())
   File "setup.py", line 14, in <module>
     from setuptools_rust import RustExtension
   File "/private/tmp/pip-build-env-gh8ot2a3/overlay/lib/python3.8/site-packages/setuptools_rust/__init__.py", line 1, in <module>
     from .build import build_rust
   File "/private/tmp/pip-build-env-gh8ot2a3/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 23, in <module>
     from setuptools.command.build import build as CommandBuild  # type: ignore[import]
 ModuleNotFoundError: No module named 'setuptools.command.build'
```
This changeset includes three substantive changes to how the formula is
generated:

1. Rust has been added as a build-time dependency. This is the root
cause of the installation failure.
2. The major.minor version (`python3.9`of the python executable is used instead of
`python3`). This prevents the installation from inadvertently using the
system Python. This occurs because Homebrew only symlinks a `python3`
executable for the latest version. See Homebrew/homebrew-core/107517.
3. Adds `--allow-unsafe` to the `pip-compile` step. This is a noop
because we aren't pinning setuptools.