Fix unit tests on Python 3.11 (#3456)
* Add 3.11 to feature test workflows

Includes 3.11 in our feature tests. Adds the continue-on-error key to
bypass Windows failures until lxml/lxml 356 is resolved.

* Update mock.patch namespaces for 3.11

Because class paths are used in Task definitions we go into import
contortions to preserve them[^1]. 3.11 includes an update that replaces
`unittest.mock._importer` with `pkgutil.resolve_name`, breaking
mock.patch in several tests. For example:

```python-console
Python 3.11.0 (main, Nov 29 2022, 08:46:07) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> clspth = "cumulusci.tasks.salesforce.Deploy.__call__"
>>> import pkgutil
>>> getter = lambda: pkgutil.resolve_name(clspth)
>>> target = getter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
  File "/Users/jestevez/.pyenv/versions/3.11.0/lib/python3.11/pkgutil.py", line 715, in resolve_name
    result = getattr(result, p)
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'cumulusci.tasks.salesforce.Deploy' has no attribute '__call__'. Did you mean: '__file__'?
>>> # However
>>> from cumulusci.tasks.salesforce import Deploy
>>> getattr(Deploy, '__call__')
<function BaseTask.__call__ at 0x1113b7560>
```

Updating our patches to point at the right namespace works for most of
the mocks on 3.8+.

[^1]: Read "contortions" as "I don't understand them."

* Update create_task_fixture for 3.11

Python 3.11 removed pathlib._Accessor in python/cpython 25701. This
broke our patch when it replaced a call to `os.getcwd()` with
`Path.cwd()` in `Path.absolute()`. As a classmethod `Path.cwd()`
receives the class as its implicit first argument meaning we can have 0
or 1 arguments.

* Update enum assert for 3.11

The behavior of string enums has changed in 3.11 [what's new]:

> Changed Enum.__format__() (the default for format(), str.format() and
> f-strings) of enums with mixed-in types (e.g. int, str) to also include
> the class name in the output, not just the member’s key. This matches
> the existing behavior of enum.Enum.__str__(), returning e.g.
> 'AnEnum.MEMBER' for an enum AnEnum(str, Enum) instead of just 'MEMBER'.

This almost certainly explains the packaging bugs we've seen.

[what's new]: https://docs.python.org/3.11/whatsnew/3.11.html#enum

Co-authored-by: Brandon Parker <brandon.parker@salesforce.com>
Co-authored-by: Paul Prescod <pprescod@salesforce.com>