Update mock.patch namespaces for 3.11
Because class paths are used in Task definitions we go into import
contortions to preserve them[^1]. 3.11 includes an update that replaces
`unittest.mock._importer` with `pkgutil.resolve_name`, breaking
mock.patch in several tests. For example:

```python-console
Python 3.11.0 (main, Nov 29 2022, 08:46:07) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> clspth = "cumulusci.tasks.salesforce.Deploy.__call__"
>>> import pkgutil
>>> getter = lambda: pkgutil.resolve_name(clspth)
>>> target = getter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
  File "/Users/jestevez/.pyenv/versions/3.11.0/lib/python3.11/pkgutil.py", line 715, in resolve_name
    result = getattr(result, p)
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'cumulusci.tasks.salesforce.Deploy' has no attribute '__call__'. Did you mean: '__file__'?
>>> # However
>>> from cumulusci.tasks.salesforce import Deploy
>>> getattr(Deploy, '__call__')
<function BaseTask.__call__ at 0x1113b7560>
```

Updating our patches to point at the right namespace works for most of
the mocks on 3.8+.

[^1]: Read "contortions" as "I don't understand them."