Use 3.8 typing syntax (#3578)
Support for PEP 604 union types was added in 3.10:

```python-console
Python 3.8.16 (default, Dec  8 2022, 14:03:21)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> mystr: str | None = None or str
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

(Also, :walrus:)