"None" check to prevent error
Hi team --

I was having issues running `cci task run update_admin_profile` after I specified page layout config per #3243:
```
Traceback (most recent call last):
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/cli/cci.py", line 91, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/cli/task.py", line 181, in run_task
    task()
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/core/tasks.py", line 172, in __call__
    self.result = self._run_task()
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/tasks/metadata_etl/base.py", line 171, in _run_task
    self._transform()
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/tasks/metadata_etl/base.py", line 339, in _transform
    transformed_xml = self._transform_entity(tree, unquoted_api_name)
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/tasks/salesforce/update_profile.py", line 224, in _transform_entity
    self._set_record_types(tree, api_name)
  File "/usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/tasks/salesforce/update_profile.py", line 295, in _set_record_types
    if elem.find("recordType").text == rt["record_type"]:
AttributeError: 'NoneType' object has no attribute 'text'
> /usr/local/py-utils/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/tasks/salesforce/update_profile.py(295)_set_record_types()
-> if elem.find("recordType").text == rt["record_type"]:
```

After digging, I realized that when Extracting Existing Metadata, the xml extraction included a `layoutAssignments` where `layout` was defined, but NOT `recordType`:
```
<layoutAssignments>
        <layout>CustomObject__c-My Layout</layout>
</layoutAssignments>
```

This proposed change adds a "None" check.