Fix error caused by supported_orgs case-sensitivity (#3277)
When running metadeploy_publish, users received an error from the REST
API:
```
Error: b'{"supported_orgs":["\\"persistent\\" is not a valid choice."]}'
```

because the Plan.supported_orgs field in MDP is case-sensitive. We
switch to title case on client-side.